# Generated by Django 5.0.6 on 2024-07-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moduleexercise',
            old_name='exercises_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='moduleexercise',
            old_name='num_attempts',
            new_name='number_of_attempts',
        ),
        migrations.RenameField(
            model_name='moduleexercise',
            old_name='num_questions',
            new_name='number_of_hints',
        ),
        migrations.RenameField(
            model_name='moduleexercise',
            old_name='description',
            new_name='title',
        ),
        migrations.AddField(
            model_name='moduleexercise',
            name='hints',
            field=models.JSONField(default=list),
        ),
    ]
